# Generated by Django 4.1.13 on 2024-04-14 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.IntegerField()),
                ('flight_destination', models.CharField(max_length=200)),
                ('flight_capacity', models.IntegerField()),
                ('flight_population', models.IntegerField()),
            ],
        ),
    ]
