# Generated by Django 4.1.13 on 2024-04-17 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flight',
            options={'managed': False},
        ),
    ]
