# Generated by Django 4.1.13 on 2024-04-20 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0002_alter_flight_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='flight',
            table='backendapp_flight',
        ),
    ]
