# Generated by Django 4.1.13 on 2024-04-15 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('admin', 'Admin'), ('worker', 'Worker'), ('visitor', 'Visitor')], max_length=20)),
            ],
            options={
                'db_table': 'Login',
            },
        ),
    ]
