# Generated by Django 4.1.13 on 2024-04-15 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_userprofile_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofile',
            table='login_userprofile',
        ),
    ]
