# Generated by Django 4.1.13 on 2024-04-17 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_alter_userprofile_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofile',
            table='users',
        ),
    ]
