# Generated by Django 4.1.13 on 2024-05-03 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_alter_userprofile_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofile',
            table='login_userprofile',
        ),
    ]
